import Head from "next/head";
import { Container } from "react-bootstrap";
import NotAllowed from "~/Components/NotAllowed";
import useFirma from "~/Hooks/useFirma";
import { MAIN_TITLE } from "~/conf";

export default function Home() {
  const allowed = useFirma();

  return (
    <>
      <Head>
        <title>Dashboard - {MAIN_TITLE}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container className="mt-3">
          <h1 className="text-center">{MAIN_TITLE}</h1>
          <p className="text-center">
            <small className="text-muted">
              <b>K</b>urse zur <b>E</b>rhöhung des <b>V</b>erständnisses für{" "}
              <b>I</b>nformations- und <b>N</b>etzwerksicherheit
            </small>
          </p>
        </Container>
        <Container className="mt-3">
          {!allowed && <NotAllowed />}
          {allowed && <></>}
        </Container>
      </main>
    </>
  );
}
